{% set name = "uWSGI" %}
{% set version = "2.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 4cc4727258671ac5fa17ab422155e9aaef8a2008ebb86e4404b66deaae965db2
  patches:
    - patches/0001-This-adds-support-for-Python-3.12.patch

build:
  number: 4
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - icu
    - jansson
    - libpython-static
    - libxml2  # [not win]
    - openssl
    - pcre
    - pip
    - python
    - yaml
    - zlib
  run:
    - jansson
    - python

test:
  source_files:
    - tests
  commands:
    - uwsgi --plugin-list
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
