{% set name = "uWSGI" %}
{% set version = "2.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 35a30d83791329429bc04fe44183ce4ab512fcf6968070a7bfba42fc5a0552a9

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - icu
    - jansson
    - libpython-static  # [py>=38]
    - libxml2  # [not win]
    - openssl
    - pcre
    - pip
    - python
    - yaml
    - zlib
  run:
    - jansson
    - python

test:
  source_files:
    - tests
  commands:
    - uwsgi --plugin-list
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
