{% set version = "2.0.14" %}

package:
  name: uwsgi
  version: '{{ version }}'

source:
  fn: "uwsgi-{{ version }}.tar.gz"
  url: "https://pypi.io/packages/source/u/uWSGI/uwsgi-{{ version }}.tar.gz"
  sha256: 21b3d1ef926d835ff23576193a2c60d4c896d8e21567850cf0677a4764122887

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    # - jansson  # a json parser library that should be added once available as a conda package
    - libxml2  # [unix]
    - openssl 1.0.*
    - pcre
    - yaml
    - zlib 1.2*
  run:
    - python
    # - jansson
    - libxml2  # [unix]
    - openssl 1.0.*
    - pcre
    - yaml
    - zlib 1.2*

test:
  commands:
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL2
  summary: >
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
