{% set version = "2.0.18" %}

package:
  name: uwsgi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uWSGI/uwsgi-{{ version }}.tar.gz
  sha256: 4972ac538800fb2d421027f49b4a1869b66048839507ccf0aa2fda792d99f583

build:
  number: 5
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - jansson
    - libxml2  # [not win]
    - openssl
    - pcre
    - yaml
    - zlib
    - icu
  run:
    - python
    - jansson

test:
  source_files:
    - tests
  commands:
    - uwsgi --version
    - uwsgi --plugin-list

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
