{% set name = "uWSGI" %}
{% set version = "2.0.25.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: d653d2d804c194c8cbe2585fa56efa2650313ae75c686a9d7931374d4dfbfc6e

build:
  number: 0
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - icu
    - jansson
    - libpython-static
    - libxml2  # [not win]
    - openssl
    - pcre
    - pip
    - python
    - yaml
    - zlib
  run:
    - jansson
    - python

test:
  source_files:
    - tests
  commands:
    - uwsgi --plugin-list
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
