{% set name = "uWSGI" %}
{% set version = "2.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: c12aa652124f062ac216077da59f6d247bd7ef938234445881552e58afb1eb5f

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - icu
    - jansson
    - liblzma-devel
    - libpython-static
    - libxcrypt
    - libxml2-devel  # [not win]
    - openssl
    - pcre2
    - pip
    - python
    - setuptools
    - yaml
    - zlib
  run:
    - jansson
    - python

test:
  requires:
    - procps-ng  # [linux]
  source_files:
    - tests
  commands:
    - uwsgi --plugin-list
    - uwsgi --version

about:
  home: https://github.com/unbit/uwsgi
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
    - xhochy
