schema_version: 1

context:
  name: uWSGI
  version: 2.0.31

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: e8f8b350ccc106ff93a65247b9136f529c14bf96b936ac5b264c6ff9d0c76257

build:
  number: 0
  skip: win
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: 
        - python
        - cross-python_${{ target_platform }}
  host:
    - icu
    - jansson
    - liblzma-devel
    - libpython-static
    - libxcrypt
    - if: not win
      then: libxml2-devel
    - openssl
    - pcre2
    - pip
    - python
    - setuptools
    - yaml
    - zlib
  run:
    - jansson
    - python

tests:
  - files:
      source:
        - tests
      recipe:
        - run_test.sh
    requirements:
      run:
        - if: linux
          then: procps-ng
    script:
      - ./run_test.sh
      - uwsgi --version

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: |
    The uWSGI project aims at developing a full stack for building hosting
    services. Application servers (for various programming languages and
    protocols), proxies, process managers and monitors are all implemented.
  homepage: https://github.com/unbit/uwsgi

extra:
  recipe-maintainers:
    - kalefranz
    - ocefpaf
    - xhochy
