travis:
  secure:
    BINSTAR_TOKEN: EjTUl4OhVFcAqylNo0BCxKO4dUneNpNd/YrXIDNYrpwzrMX2R6hr5bUP5KRPwXlyTWNHqzeLSbcHkUBAgl4/8dUre3tolkPksrdMpVKAubHr/mHM7dnHOdQV2y8TlR7UPlTDPYvOmHMC8XgWTnrPCcFwEt+Jurp7/wGPCxIgWkImQ21Q9MU2lW3wu/rEm0k/jyH5uoRKqrNxiXaeWewBwNxLCI+DPpmEJGUQNvzWENRMBY8XA1qRGByz+fVFIOCNrLE9G9avCa4hMeOiOsAEgbIY0G3b9kDxZNh67hmXNQne3Ii0vbsWnyK1eiwZvUlXCLKMMEm2TUm3qL4ZPZq0QSGXBzEMNrF4YJhVMDQmglDSl4NJD3oc3wVTvmIS9NSI+vodTjxWJXLv1DoG5JG09/FcOV6yKet68szov2k2A84DicYzVfhphx6j0NZkCqaX5ZSs1jIQS9Yx3KT6G1U/p3r3m1k2SbWjUPe+nMD2YciDodLypT2plw1/mugVCQJ8/m9wJXqj1/c5kEojOZGd0MnQIPoiYDK2uaWSM2bLXetrOgTJUvsuIpQnYIlv1p866Ft0XwdAwaI4GpMs/+mHLd7WOTnDC1eKYihzggWatvQv3AgzI/mq7OLhs6UEnI3tEzVIrOZWY1OrX6zzbXmizBvq6DJmHX1/vVaJqiqZNB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: circle
